In [1]:
import pandas as pd

### Gender Table

In [2]:
gender = pd.read_csv('gender_submission.csv')

In [3]:
gender.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

### Testing Table

In [4]:
test = pd.read_csv('test.csv')

In [5]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

### Training Table

In [7]:
train = pd.read_csv('train.csv')

In [8]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=200,
    random_state=42 
                            )
# Take sex in account
train["Sex"] = train["Sex"].map({"male": 0, "female": 1})
test["Sex"] = test["Sex"].map({"male": 0, "female": 1})

features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]

X = train[features].fillna(train[features].median())
Y = train["Survived"]

clf.fit(X, Y)

testX = test[features].fillna(test[features].median())

predict = clf.predict(testX)

In [21]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": predict
})

submission.to_csv("randforest_submission.csv", index=False)

### Gradient Boost

In [29]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=200, random_state=1, learning_rate=0.2)
gb.fit(X, Y)
gb_predict = gb.predict(testX)

In [30]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": gb_predict
})

submission.to_csv("gb_submission.csv", index=False)

### XGBoost

In [39]:
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
bst.fit(X, Y)
bst_predict = bst.predict(testX)

In [40]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": bst_predict
})

submission.to_csv("bst_submission.csv", index=False)